db.url=jdbc:sqlserver://docubridge-server.database.windows.net:1433;database=docubridge-db;user=docuadmin@docubridge-server;password=DocuPass123!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
azure.translator.key=9ITDbGrW6gNAJIUhly1SgbCZPm0yaAXrAx8p4zl2QByY8qVjmFovJQQJ99CCACBsN54XJ3w3AAAbACOGHRR9
azure.translator.region=canadacentral
azure.translator.endpoint=https://api.cognitive.microsofttranslator.com/